### ISSUE TITLE
ArgumentError (path name contains null byte)

### ISSUE THREAD

**Issue by sumonmg** [koshigoe/brick_ftp#128]
Hello there,

I've been trying to upload file with following code in Rails controller:

```
file = params[:file]
path = "dev/free_trial/#{file.original_filename}"
client = BrickFTP::Client.new
client.upload_file(path, file.read)
```

But it is giving me this error: `ArgumentError (path name contains null byte)`

I'm submitting form via Postman, attached screenshot showing how I'm submitting the file.

![Postman screenshot](https://user-images.githubusercontent.com/11157684/65317812-69e88680-db94-11e9-96c0-5ebc1df0bcae.png)

Any idea what wrong I'm doing?

**Comment by sumonmg** [comment]
Ahh! I found it. Instead of sending file data I just need to send the file. `client.upload_file(path, file)` instead of `client.upload_file(path, file.read)`
Problem solved.

This gem is great but I really think the documentation needs to be updated with more example calls.

**Comment by pierreyves-lebrun** [comment]
I made the same mistake 2 years ago when playing with the gem.

I guess the author intention is to allow any form of data to be uploaded, which is a good thing however the lack of documentation can be misleading. :-)
