### ISSUE TITLE
CGI escaping returns incorrect URI

### ISSUE THREAD

**Issue by terencedignon** [koshigoe/brick_ftp#55]
I found that CGI escaping returns 404 errors on getting a file show when the filename includes spaces. 

After toying around with it I fixed it by preferring URI.escape over CGI.escape.

**Comment by koshigoe** [comment]
I released fixed version.

- https://rubygems.org/gems/brick_ftp/versions/0.4.1

I hope this version resolve your problem.

**Comment by terencedignon** [comment]
@koshigoe Thank you!
