### ISSUE TITLE
list_folders function error

### ISSUE THREAD

**Issue by pierreyves-lebrun** [koshigoe/brick_ftp#68]
brickFtpUploader = BrickFTP::Client.new 
brickFtpResources = brickFtpUploader.list_folders(path: "/")

When listing the root of a BrickFtp server with the list_folders function, the following error occurs:

App 32339 stderr: NameError - `@subfolders_locked?' is not allowed as an instance variable name:
App 32339 stderr:       /usr/local/rvm/gems/ruby-2.4.0/gems/brick_ftp-0.5.0/lib/brick_ftp/api/base.rb:43:in `instance_variable_set'
App 32339 stderr:       /usr/local/rvm/gems/ruby-2.4.0/gems/brick_ftp-0.5.0/lib/brick_ftp/api/base.rb:43:in `block in initialize'
App 32339 stderr:       /usr/local/rvm/gems/ruby-2.4.0/gems/brick_ftp-0.5.0/lib/brick_ftp/api/base.rb:43:in `each'
App 32339 stderr:       /usr/local/rvm/gems/ruby-2.4.0/gems/brick_ftp-0.5.0/lib/brick_ftp/api/base.rb:43:in `initialize'
App 32339 stderr:       /usr/local/rvm/gems/ruby-2.4.0/gems/brick_ftp-0.5.0/lib/brick_ftp/api/base.rb:18:in `new'
App 32339 stderr:       /usr/local/rvm/gems/ruby-2.4.0/gems/brick_ftp-0.5.0/lib/brick_ftp/api/base.rb:18:in `block in all'
App 32339 stderr:       /usr/local/rvm/gems/ruby-2.4.0/gems/brick_ftp-0.5.0/lib/brick_ftp/api/base.rb:18:in `map'
App 32339 stderr:       /usr/local/rvm/gems/ruby-2.4.0/gems/brick_ftp-0.5.0/lib/brick_ftp/api/base.rb:18:in `all'
App 32339 stderr:       /usr/local/rvm/gems/ruby-2.4.0/gems/brick_ftp-0.5.0/lib/brick_ftp/client.rb:305:in `list_folders'

Could you please look at the issue?

**Comment by terencedignon** [comment]
Experiencing this as well!

**Comment by terencedignon** [comment]
I believe the issue is BrickFTP has added a new key with a question mark.  Here are the params right before breaking
<img width="1346" alt="screen shot 2017-12-16 at 11 09 54 pm" src="https://user-images.githubusercontent.com/13992890/34076477-61eb78da-e2b6-11e7-889c-1d30a0c18d4d.png">

**Comment by pierreyves-lebrun** [comment]
Nice finding, that is what I wondered as this function used to work perfectly fine until 1-2 days ago.

I am kind of surprised BrickFtp didn’t make that change in a separate version of their API.

**Comment by koshigoe** [comment]
I merged #69, and released fixed version [v0.5.1](https://rubygems.org/gems/brick_ftp/versions/0.5.1).

**Comment by terencedignon** [comment]
Thanks!
