### ISSUE TITLE
Unexpected behaviour when calling the to_json method on an UploadingSession object

### ISSUE THREAD

**Issue by pierreyves-lebrun** [koshigoe/brick_ftp#91]
# This is a Bug Report.

## Description

* What went wrong?
Calling the to_json method on an UploadingSession object is endless

* What did you expect should have happened?
I was expecting the to_json function to return a serialised version of the object

* What was the config you used?
I replicated the issue in IRB with the following:
```
require "active_record"
require "brick_ftp"

session = BrickFTP::API::FileOperation::UploadingSession.create(path: '/test-koshigoe/multi-part-uploaded.txt')
session.to_json

```
* What stacktrace or error message from your provider did you see?
No stacktrace or error message is displayed, the to_json method call just never ends.

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
Centos 7
* ***Stack Trace***:
* ***Provider Error messages***:

Please note that the problem doesn't happen when not requiring active_record.
Only when requiring active_record (version 5.4.1), to_json method calls become endless.

**Comment by koshigoe** [comment]
The activesupport implements `Enumerable#as_json` and it calls `#to_a`.
So, the `BrickFTP::API::FileOperation::UploadingSession#as_json` sends HTTP request `available_parts` times.

I fixes this bug by https://github.com/koshigoe/brick_ftp/pull/92

The `BrickFTP::API::FileOperation::UploadingSession#as_json` returns current `BrickFTP::API::FileOperation::UploadingSession#properties`. (Not Array)
